name: KillDeathRatio
version: 1.0.0
author: ByteForge88
api: 5.41.0
main: byteforge88\kdr\Core

permissions:
  killdeathratio.kdr:
    default: true
  killdeathratio.seekdr:
    default: true
  killdeathratio.killleaderboard:
    default: true
  killdeathratio.deathleaderboard:
    default: true
  killdeathratio.killfloatingtext:
    default: op
  killdeathratio.deathfloatingtext:
    default: op